### PR TITLE
Nrfjprog support

### PR DESCRIPTION
**Pull request by jeanmatthieud**
Adds the possibility to use the nrfjprog tool of Nordic Semi (nrf5x command line tools) by setting `upload_protocol = nrfjprog`in the platformio.ini file env configuration.

### CODE REVIEW

**Comment by ivankravets** [comment]
Where are the binaries of this tool for all architectures/OS?

**Comment by zerog2k** [comment]
I would like to see nrfjprog or something similar like https://github.com/NordicPlayground/nRF5-universal-prog, but afaik they all require jlink binaries, e.g. dll

@ivankravets 

re: binaries, this is tricky, as you have the nrfjprog binaries from nordic plus the jlink software. Not sure of the redistribution issues here?
Is it a platformio requirement that every and all frameworks, toolchains, and tools, be redistributable? Is it ever acceptable that they have to be installed by user, and some minimum configuration (in path, or setting to point to it?) required to be done by user?

**Comment by ivankravets** [comment]
You can configure a custom uploader via http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-uploader

**Comment by jeanmatthieud** [comment]
@ivankravets
[nRF5x-Command-Line-Tools-Linux32](https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-Linux32/52615)
[nRF5x-Command-Line-Tools-Linux64](https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-Linux64/51386)
[nRF5x-Command-Line-Tools-OSX](https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-OSX/53402)
[nRF5x-Command-Line-Tools-Win32(https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-Win32/33444)

**Comment by ivankravets** [comment]
@jeanmatthieud  THANK YOU SO MUCH for this PR and links to binaries.

Please re-test with the latest version of dev/platform
```ini
[env:..]
platform = https://github.com/platformio/platform-nordicnrf51.git
upload_protocol = nrfjprog
```

**Comment by zerog2k** [comment]
btw, i found a way to do this via extra_scripts... an example (on an experimental 8051 platform, using stcgal):
https://github.com/zerog2k/stc_diyclock/blob/platformio/post_extra_script.py#L22-L36

**Pull request closed without merging**
