### PR TITLE
Add nRF52-DK

### PR DESCRIPTION
**Pull request by amq**

### CODE REVIEW

**Comment by amq** [comment]
As I'm looking at it now, this should probably be in a separate platform.

platform-nordicnrf51 = https://github.com/ARMmbed/mbed-os/tree/master/targets/TARGET_NORDIC/TARGET_MCU_NRF51822

platform-nordicnrf5 = https://github.com/ARMmbed/mbed-os/tree/master/targets/TARGET_NORDIC/TARGET_NRF5

**Comment by ivankravets** [comment]
Hi,

Yes, this is new development platform named `platform-nordicnrf52`. Do you have this nRF52-DK?

**Comment by amq** [comment]
I will receive a board based on it today:
https://www.u-blox.com/en/product/nina-b1
https://github.com/ARMmbed/mbed-os/pull/3128

**Comment by amq** [comment]
mbed is now getting a support for this nRF52-based board https://github.com/ARMmbed/mbed-os/pull/3291, so I will be glad to test platformio with it

**Pull request closed without merging**
